name: Deploy preview web area

on:
  push:
    branches: [master]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    if: startsWith(github.repository, 'opensciencegrid/')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Remove prod configurations
        run: |
          rm CNAME
          sed -i "s|baseurl: ''|baseurl: '/web-preview'|" _config.yml
          git config user.name "Automatic preview publish"
          git config user.email "help@opensciencegrid.org"
          git commit -am "GHA: $GITHUB_REPOSITORY #$GITHUB_RUN_NUMBER)"

      # SSH key recipe from https://www.webfactory.de/blog/use-ssh-key-for-private-repositories-in-github-actions
      - name: Deploy web page preview
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a "$SSH_AUTH_SOCK" > /dev/null
          ssh-add - <<< "${{ secrets.PREVIEW_DEPLOY_KEY }}"
          git remote add web-preview "git@github.com:opensciencegrid/web-preview.git"
          git push -f web-preview HEAD:gh-pages
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
